
#!/usr/bin/env python3
"""
QuickPOS Pro - Export Fix Script
Run from ~/myapp:  python3 write_export_files.py
"""
import os

def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    size = os.path.getsize(path)
    print(f"  DONE: {path} ({size} bytes)")

print("=" * 60)
print("  QuickPOS Pro - Writing Export Fix Files")
print("=" * 60)
print()

file1 = (
    "// lib/utils/web_download_stub.dart\n"
    "// FIXED: Uses share_plus instead of throwing UnsupportedError\n"
    "import 'dart:io';\n"
    "import 'dart:typed_data';\n"
    "import 'package:path_provider/path_provider.dart';\n"
    "import 'package:share_plus/share_plus.dart';\n"
    "\n"
    "Future<void> _shareFile(Uint8List bytes, String filename, String mimeType) async {\n"
    "  final dir = await getTemporaryDirectory();\n"
    "  final filePath = '${dir.path}/$filename';\n"
    "  final file = File(filePath);\n"
    "  await file.writeAsBytes(bytes);\n"
    "  await Share.shareXFiles(\n"
    "    [XFile(filePath, mimeType: mimeType)],\n"
    "    subject: filename,\n"
    "  );\n"
    "}\n"
    "\n"
    "void downloadPdf(Uint8List bytes, String filename) {\n"
    "  _shareFile(bytes, filename, 'application/pdf');\n"
    "}\n"
    "\n"
    "void downloadExcel(Uint8List bytes, String filename) {\n"
    "  _shareFile(bytes, filename,\n"
    "      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');\n"
    "}\n"
    "\n"
    "void downloadCsv(Uint8List bytes, String filename) {\n"
    "  _shareFile(bytes, filename, 'text/csv');\n"
    "}\n"
)
write_file("lib/utils/web_download_stub.dart", file1)

file2 = (
    "// lib/utils/web_download.dart\n"
    "// ignore: avoid_web_libraries_in_flutter\n"
    "import 'dart:html' as html;\n"
    "import 'dart:typed_data';\n"
    "\n"
    "void _download(Uint8List bytes, String filename, String mimeType) {\n"
    "  final blob = html.Blob([bytes], mimeType);\n"
    "  final url = html.Url.createObjectUrlFromBlob(blob);\n"
    "  final anchor = html.AnchorElement(href: url);\n"
    "  anchor.download = filename;\n"
    "  anchor.click();\n"
    "  html.Url.revokeObjectUrl(url);\n"
    "}\n"
    "\n"
    "void downloadPdf(Uint8List bytes, String filename) {\n"
    "  _download(bytes, filename, 'application/pdf');\n"
    "}\n"
    "\n"
    "void downloadExcel(Uint8List bytes, String filename) {\n"
    "  _download(bytes, filename,\n"
    "      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');\n"
    "}\n"
    "\n"
    "void downloadCsv(Uint8List bytes, String filename) {\n"
    "  _download(bytes, filename, 'text/csv');\n"
    "}\n"
)
write_file("lib/utils/web_download.dart", file2)

file3 = (
    "// lib/utils/export_helper.dart\n"
    "import 'dart:convert';\n"
    "import 'dart:typed_data';\n"
    "import 'package:excel/excel.dart' as exc;\n"
    "import 'package:pdf/pdf.dart';\n"
    "import 'package:pdf/widgets.dart' as pw;\n"
    "import 'web_download_stub.dart' if (dart.library.html) 'web_download.dart';\n"
    "\n"
    "class ExportHelper {\n"
    "  // Export as real Excel (.xlsx)\n"
    "  static void exportExcel({\n"
    "    required List<String> headers,\n"
    "    required List<List<String>> rows,\n"
    "    required String sheetName,\n"
    "    required String fileName,\n"
    "  }) {\n"
    "    final excel = exc.Excel.createExcel();\n"
    "    final sheet = excel[sheetName];\n"
    "    if (sheetName != 'Sheet1') {\n"
    "      excel.delete('Sheet1');\n"
    "    }\n"
    "    for (int i = 0; i < headers.length; i++) {\n"
    "      sheet.cell(exc.CellIndex.indexByColumnRow(columnIndex: i, rowIndex: 0))\n"
    "        ..value = exc.TextCellValue(headers[i])\n"
    "        ..cellStyle = exc.CellStyle(bold: true);\n"
    "    }\n"
    "    for (int r = 0; r < rows.length; r++) {\n"
    "      for (int c = 0; c < rows[r].length; c++) {\n"
    "        sheet.cell(exc.CellIndex.indexByColumnRow(columnIndex: c, rowIndex: r + 1))\n"
    "          ..value = exc.TextCellValue(rows[r][c]);\n"
    "      }\n"
    "    }\n"
    "    final bytes = excel.save();\n"
    "    if (bytes != null) {\n"
    "      downloadExcel(Uint8List.fromList(bytes), fileName);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  // Export as PDF\n"
    "  static Future<void> exportPdf({\n"
    "    required String title,\n"
    "    required List<String> headers,\n"
    "    required List<List<String>> rows,\n"
    "    required String fileName,\n"
    "    String? subtitle,\n"
    "  }) async {\n"
    "    final pdf = pw.Document();\n"
    "    pdf.addPage(\n"
    "      pw.MultiPage(\n"
    "        pageFormat: PdfPageFormat.a4.landscape,\n"
    "        margin: const pw.EdgeInsets.all(20),\n"
    "        build: (context) => [\n"
    "          pw.Column(\n"
    "            crossAxisAlignment: pw.CrossAxisAlignment.start,\n"
    "            children: [\n"
    "              pw.Text(title, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),\n"
    "              if (subtitle != null)\n"
    "                pw.Text(subtitle, style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700)),\n"
    "              pw.SizedBox(height: 4),\n"
    "              pw.Text('Generated: ' + DateTime.now().toString().substring(0, 19),\n"
    "                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500)),\n"
    "              pw.SizedBox(height: 12),\n"
    "            ],\n"
    "          ),\n"
    "          pw.TableHelper.fromTextArray(\n"
    "            headers: headers,\n"
    "            data: rows,\n"
    "            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8),\n"
    "            cellStyle: const pw.TextStyle(fontSize: 7),\n"
    "            cellAlignment: pw.Alignment.centerLeft,\n"
    "            headerDecoration: const pw.BoxDecoration(color: PdfColors.teal50),\n"
    "            border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),\n"
    "            cellPadding: const pw.EdgeInsets.all(4),\n"
    "          ),\n"
    "        ],\n"
    "      ),\n"
    "    );\n"
    "    final data = await pdf.save();\n"
    "    downloadPdf(data, fileName);\n"
    "  }\n"
    "\n"
    "  // Export as CSV file\n"
    "  static void exportCsvFile({\n"
    "    required List<String> headers,\n"
    "    required List<List<String>> rows,\n"
    "    required String fileName,\n"
    "  }) {\n"
    "    final buf = StringBuffer();\n"
    "    buf.writeln(headers.join(','));\n"
    "    for (final row in rows) {\n"
    "      buf.writeln(row.map((cell) {\n"
    "        if (cell.contains(',') || cell.contains('\"')) {\n"
    "          return '\"' + cell.replaceAll('\"', '\"\"') + '\"';\n"
    "        }\n"
    "        return cell;\n"
    "      }).join(','));\n"
    "    }\n"
    "    final bytes = Uint8List.fromList(utf8.encode(buf.toString()));\n"
    "    downloadCsv(bytes, fileName);\n"
    "  }\n"
    "}\n"
)
write_file("lib/utils/export_helper.dart", file3)

print()
print("=" * 60)
print("  ALL 3 FILES WRITTEN SUCCESSFULLY!")
print("=" * 60)
print()
print("NEXT STEPS:")
print("Open lib/screens/reports/sales_analytics_screen.dart")
print("in the Firebase Studio CODE EDITOR and make these changes:")
print()
print("STEP 1: Add this import at the top (after other imports):")
print("  import '../../utils/export_helper.dart';")
print()
print("STEP 2: Add these 4 methods ABOVE the existing _exportCSV method.")
print("STEP 3: Replace the old _exportCSV method.")
print("STEP 4: Replace the bottomNavigationBar with 3 buttons.")
print()
print("See PATCH_INSTRUCTIONS.txt for full code to copy-paste.")
print()
# Write patch instructions file
patch = (
    "============================================================\n"
    "PATCH INSTRUCTIONS for sales_analytics_screen.dart\n"
    "============================================================\n"
    "\n"
    "STEP 1: Add import at the top:\n"
    "\n"
    "  import '../../utils/export_helper.dart';\n"
    "\n"
    "============================================================\n"
    "STEP 2: Add these methods ABOVE the _exportCSV method:\n"
    "============================================================\n"
    "\n"
    "  // -- Export helpers --\n"
    "\n"
    "  List<String> _getHeaders() {\n"
    "    final tab = _tabCtrl.index;\n"
    "    if (tab == 0) return ['Name', 'SKU', 'Category', 'Units', 'Sales', 'Transactions'];\n"
    "    if (tab == 1) return ['Category', 'Items', 'Units', 'Sales', 'Transactions', 'ADS', 'ATC'];\n"
    "    return ['Period', 'TXN', 'Units', 'Gross', 'ActiveDays', 'ADS', 'ATC', 'ATV', 'IPB', 'Profit', 'Margin'];\n"
    "  }\n"
    "\n"
    "  List<List<String>> _getRows() {\n"
    "    final tab = _tabCtrl.index;\n"
    "    if (tab == 0) {\n"
    "      return _itemSales.map((item) => [\n"
    "        item.name, item.sku, item.category,\n"
    "        '${item.totalUnits}', item.totalSales.toStringAsFixed(2), '${item.txnCount}',\n"
    "      ]).toList();\n"
    "    }\n"
    "    if (tab == 1) {\n"
    "      final calDays = _getTotalCalendarDays();\n"
    "      return _categorySales.map((cat) => [\n"
    "        cat.name, '${cat.itemCount}', '${cat.totalUnits}',\n"
    "        cat.totalSales.toStringAsFixed(2), '${cat.txnCount}',\n"
    "        (cat.totalSales / calDays).toStringAsFixed(2),\n"
    "        (cat.txnCount / calDays).toStringAsFixed(1),\n"
    "      ]).toList();\n"
    "    }\n"
    "    final rows = _buildTrendRows();\n"
    "    return rows.map((r) => [\n"
    "      r.label, '${r.txnCount}', '${r.units}',\n"
    "      r.sales.toStringAsFixed(2), '${r.days}',\n"
    "      r.ads.toStringAsFixed(2), r.atc.toStringAsFixed(1),\n"
    "      r.atv.toStringAsFixed(2), r.ipb.toStringAsFixed(1),\n"
    "      r.profit.toStringAsFixed(2), '${r.margin.toStringAsFixed(1)}%',\n"
    "    ]).toList();\n"
    "  }\n"
    "\n"
    "  Future<void> _exportExcel() async {\n"
    "    final tab = _tabCtrl.index;\n"
    "    final names = ['ByItem', 'ByCategory', 'Trends'];\n"
    "    ExportHelper.exportExcel(\n"
    "      headers: _getHeaders(),\n"
    "      rows: _getRows(),\n"
    "      sheetName: names[tab],\n"
    "      fileName: 'Sales_${names[tab]}_${DateTime.now().millisecondsSinceEpoch}.xlsx',\n"
    "    );\n"
    "    if (mounted) _snack('Excel exported!');\n"
    "  }\n"
    "\n"
    "  Future<void> _exportPdf() async {\n"
    "    final tab = _tabCtrl.index;\n"
    "    final names = ['By Item', 'By Category', 'Trends'];\n"
    "    await ExportHelper.exportPdf(\n"
    "      title: 'Sales Analytics - ${names[tab]}',\n"
    "      headers: _getHeaders(),\n"
    "      rows: _getRows(),\n"
    "      fileName: 'Sales_${names[tab].replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.pdf',\n"
    "      subtitle: 'Period: $_dateFilter',\n"
    "    );\n"
    "    if (mounted) _snack('PDF exported!');\n"
    "  }\n"
    "\n"
    "============================================================\n"
    "STEP 3: REPLACE the old _exportCSV method with this:\n"
    "============================================================\n"
    "\n"
    "  Future<void> _exportCSV() async {\n"
    "    final tab = _tabCtrl.index;\n"
    "    final names = ['ByItem', 'ByCategory', 'Trends'];\n"
    "    ExportHelper.exportCsvFile(\n"
    "      headers: _getHeaders(),\n"
    "      rows: _getRows(),\n"
    "      fileName: 'Sales_${names[tab]}_${DateTime.now().millisecondsSinceEpoch}.csv',\n"
    "    );\n"
    "    if (mounted) _snack('CSV exported!');\n"
    "  }\n"
    "\n"
    "============================================================\n"
    "STEP 4: REPLACE the bottomNavigationBar with this:\n"
    "============================================================\n"
    "\n"
    "      bottomNavigationBar: Container(\n"
    "        padding: const EdgeInsets.all(12),\n"
    "        decoration: BoxDecoration(\n"
    "          color: Colors.white,\n"
    "          boxShadow: [\n"
    "            BoxShadow(\n"
    "                color: Colors.black.withAlpha(20),\n"
    "                blurRadius: 8,\n"
    "                offset: const Offset(0, -2))\n"
    "          ],\n"
    "        ),\n"
    "        child: SafeArea(\n"
    "          child: Row(children: [\n"
    "            Expanded(\n"
    "                child: ElevatedButton.icon(\n"
    "              onPressed: _exportExcel,\n"
    "              icon: const Icon(Icons.table_chart, size: 16),\n"
    "              label: const Text('Excel',\n"
    "                  style: TextStyle(\n"
    "                      fontWeight: FontWeight.bold, fontSize: 13)),\n"
    "              style: ElevatedButton.styleFrom(\n"
    "                  backgroundColor: Colors.green[700],\n"
    "                  foregroundColor: Colors.white,\n"
    "                  padding: const EdgeInsets.symmetric(vertical: 12),\n"
    "                  shape: RoundedRectangleBorder(\n"
    "                      borderRadius: BorderRadius.circular(10))),\n"
    "            )),\n"
    "            const SizedBox(width: 8),\n"
    "            Expanded(\n"
    "                child: ElevatedButton.icon(\n"
    "              onPressed: _exportPdf,\n"
    "              icon: const Icon(Icons.picture_as_pdf, size: 16),\n"
    "              label: const Text('PDF',\n"
    "                  style: TextStyle(\n"
    "                      fontWeight: FontWeight.bold, fontSize: 13)),\n"
    "              style: ElevatedButton.styleFrom(\n"
    "                  backgroundColor: Colors.red[700],\n"
    "                  foregroundColor: Colors.white,\n"
    "                  padding: const EdgeInsets.symmetric(vertical: 12),\n"
    "                  shape: RoundedRectangleBorder(\n"
    "                      borderRadius: BorderRadius.circular(10))),\n"
    "            )),\n"
    "            const SizedBox(width: 8),\n"
    "            Expanded(\n"
    "                child: ElevatedButton.icon(\n"
    "              onPressed: _exportCSV,\n"
    "              icon: const Icon(Icons.file_download, size: 16),\n"
    "              label: const Text('CSV',\n"
    "                  style: TextStyle(\n"
    "                      fontWeight: FontWeight.bold, fontSize: 13)),\n"
    "              style: ElevatedButton.styleFrom(\n"
    "                  backgroundColor: Colors.teal[700],\n"
    "                  foregroundColor: Colors.white,\n"
    "                  padding: const EdgeInsets.symmetric(vertical: 12),\n"
    "                  shape: RoundedRectangleBorder(\n"
    "                      borderRadius: BorderRadius.circular(10))),\n"
    "            )),\n"
    "          ]),\n"
    "        ),\n"
    "      ),\n"
)
write_file("PATCH_INSTRUCTIONS.txt", patch)
print("  DONE: PATCH_INSTRUCTIONS.txt")
print()
print("Open PATCH_INSTRUCTIONS.txt to see the code to add!")
